language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

sudo: true

before_install:
  - python --version
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
  - sudo apt-get update
  - sudo apt-get install build-essential
  - pip -V
  - pip install --upgrade pip
  - pip install setuptools
  - pip install coveralls
  - pip install numpy
  - pip install pytest
  - pip install pytest-cov

install:
  - python setup.py develop
#  - sff --help

script:
  - pytest --cov=./sfftkrw sfftkrw/unittests
#  - coverage run --include="/home/travis/build/emdb-empiar/sfftkrw/sfftkrw/*" --omit="/home/travis/build/emdb-empiar/sfftkrw/sfftkrw/schema/v*.py","/home/travis/build/emdb-empiar/sfftkrw/sfftkrw/test_data","/home/travis/build/emdb-empiar/sfftkrw/sfftkrw/unittests" `which sff` tests all -v 3

after_success:
  - coveralls
